name: "Build and Test"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on:
      - ubuntu-latest
    env:
      GRADLE_OPTS: "-Djava.security.egd=file:/dev/./urandom -Dorg.gradle.parallel=true"
    container:
      image: azul/zulu-openjdk:11
    steps:
      - name: "Install packages"
        run: apt-get update && apt-get install -y git
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: "Gradle cache"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: gradle-v1-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', '**/*.gradle*') }}
      - name: "Assemble jar"
        run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew assemble --console=plain --no-daemon
      - name: "Test if publishing works"
        run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew publishToMavenLocal --console=plain --no-daemon --stacktrace
      - name: "Tag release"
        if: github.ref == 'refs/heads/main'
        run: GRADLE_USER_HOME=$HOME/.gradle ./gradlew tagRelease --console=plain --no-daemon
